kind: Service
apiVersion: v1
metadata:
  labels: 
    app: db
  name:  db
  namespace: vote
spec:
  selector:
    app: db
  type:  ClusterIP
  ports:
  - name:  "db-service"
    port:  5432
    targetPort:  5432