kind: Service
apiVersion: v1
metadata:
  labels: 
    app: result
  name:  result
  namespace: vote
spec:
  selector:
    app: result
  type:  NodePort
  ports:
  - name:  "result-service"
    port:  5001
    targetPort:  80