kind: Service
apiVersion: v1
metadata:
  labels: 
    app: vote
  name:  vote
  namespace: vote
spec:
  selector:
    app: vote
  type:  NodePort
  ports:
  - name:  "vote-service"
    port:  5000
    targetPort:  80